### ISSUE TITLE
[FEATURE]: Simplify Karavi Observability deployment and documentation workflow

### ISSUE THREAD

**Issue by tdawe** [dell/karavi-observability#1]
**Describe the solution you'd like**
Simplify Karavi Observability deployment and documentation workflow, by maintaining a single set of instructions in the Karavi-observability repository.

Also involves the creation of the karavi-observability repository and all initial configuration for the repository that is required.

**Comment by ioeicicdsvc** [comment]
@tdawe: Thank you for submitting this issue!

The issue is currently awaiting triage. Please make sure you have given us as much context as possible.

If the maintainers determine this is a relevant issue, they will remove the needs-triage label and assign an appropriate priority label.

------------------------------------------------------------------------------------------------------------------------
We want your feedback! If you have any questions or suggestions regarding our contributing process/workflow, please reach out to us at karavi@dell.com.

**Comment by gallacher** [comment]
Released in 0.2.0 milestone
