### ISSUE TITLE
[FEATURE]: PowerFlex storage pool capacity dashboard bargauge thresholds should match the PowerFlex storage pools

### ISSUE THREAD

**Issue by atye** [dell/karavi-observability#17]
**Describe the solution you'd like**
The storage pool capacity bargauge thresholds are hardcoded. These thresholds should align with the alert thresholds defined on the PowerFlex.

**Describe alternatives you've considered**

**Additional context**

**Comment by ioeicicdsvc** [comment]
@atye: Thank you for submitting this issue!

The issue is currently awaiting triage. Please make sure you have given us as much context as possible.

If the maintainers determine this is a relevant issue, they will remove the needs-triage label and assign an appropriate priority label.

------------------------------------------------------------------------------------------------------------------------
We want your feedback! If you have any questions or suggestions regarding our contributing process/workflow, please reach out to us at karavi@dell.com.

**Comment by atye** [comment]
Grafana thresholds currently do not support value by variables; they must be hardcoded. We will not be able to support aligning the storage pool capacity threshold values with the PowerFlex storage pool alert thresholds until Grafana supports variable thresholds. 

Related issues
https://github.com/grafana/grafana/issues/922
https://github.com/grafana/grafana/issues/29497
https://github.com/grafana/grafana/issues/25313
https://github.com/grafana/grafana/issues/25127
https://github.com/grafana/grafana/issues/159
