### ISSUE TITLE
[FEATURE]: add number of collected metrics in the logs

### ISSUE THREAD

**Issue by coulof** [dell/karavi-observability#21]
**Describe the solution you'd like**
Right now the `karavi-metrics` component logs the time to collect and push the metrics.

During debugging of the `otel-collector` I wasn't sure if there was actual metrics in it.

It will help if the logs show the number of metrics processed 
```
2021/01/12 10:46:55 ExportVolumeStatistics took 28.348228ms
2021/01/12 10:47:04 Looking up system ID 31ba0b0125517f0f Name powerflex01
2021/01/12 10:47:04 gatherMetrics took 2.25µs for **XXX metrics**
2021/01/12 10:47:04 pushMetrics took 812ns for **XXX metrics**
```

**Comment by ioeicicdsvc** [comment]
@coulof: Thank you for submitting this issue!

The issue is currently awaiting triage. Please make sure you have given us as much context as possible.

If the maintainers determine this is a relevant issue, they will remove the needs-triage label and assign an appropriate priority label.

------------------------------------------------------------------------------------------------------------------------
We want your feedback! If you have any questions or suggestions regarding our contributing process/workflow, please reach out to us at karavi@dell.com.

**Comment by gallacher** [comment]
Duplicate of #15
