### ISSUE TITLE
[FEATURE]: Serviceability - Karavi Observability issues can be easily troubleshooted/diagnosed with non-disruptive config updates

### ISSUE THREAD

**Issue by tdawe** [dell/karavi-observability#33]
**Describe the solution you'd like**
- There is troubleshooting documentation in place to facilitate how to diagnose an issue with Karavi Observability
- Logging is updated to facilitate easy tracing of issues
- Logging should describe the current operation/execution/workflow step so returned errors have more context
- Setting the granularity of logging should be available, non-disruptively
- Metrics are collected to indicate how much time is spent in various functions.  This will also facilitate performance/scalability testing.
- Karavi Observability configuration changes can be made without bringing the services down (Config Maps)
- Logging standards are revisited and shared to properly for a set of logging standards for Ecosystems Integration
- Logs should be readily/easily available for support, and/or the customer, to download

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ioeicicdsvc** [comment]
@tdawe: Thank you for submitting this issue!

The issue is currently awaiting triage. Please make sure you have given us as much context as possible.

If the maintainers determine this is a relevant issue, they will remove the needs-triage label and assign an appropriate priority label.

------------------------------------------------------------------------------------------------------------------------
We want your feedback! If you have any questions or suggestions regarding our contributing process/workflow, please reach out to us at karavi@dell.com.
