### ISSUE TITLE
[BUG]: Security GitHub action needs "quiet" arg removed

### ISSUE THREAD

**Issue by hoppea2** [dell/karavi-observability#38]
**Describe the bug**
Security GitHub action needs "quiet" arg removed

**Additional context**
See https://github.com/dell/karavi-resiliency/pull/27 as an example fix

**Comment by ioeicicdsvc** [comment]
@hoppea2: Thank you for submitting this issue!

The issue is currently awaiting triage. Please make sure you have given us as much context as possible.

If the maintainers determine this is a relevant issue, they will remove the needs-triage label and assign an appropriate priority label.

------------------------------------------------------------------------------------------------------------------------
We want your feedback! If you have any questions or suggestions regarding our contributing process/workflow, please reach out to us at karavi@dell.com.

**Comment by ioeicicdsvc** [comment]
link: 2776
