### ISSUE TITLE
[FEATURE]: Karavi Observability Support for OpenShift

### ISSUE THREAD

**Issue by gallacher** [dell/karavi-observability#4]
**Describe the feature**
This feature involves Karavi Observability supporting OpenShift versions 4.5, 4.6. 

Karavi Observability has been properly tested to qualify support for OpenShift 4.5, 4.6.

As such, the documentation is updated to reflect the supported versions of OpenShift.

**Comment by ioeicicdsvc** [comment]
@gallacher: Thank you for submitting this issue!

The issue is currently awaiting triage. Please make sure you have given us as much context as possible.

If the maintainers determine this is a relevant issue, they will remove the needs-triage label and assign an appropriate priority label.

------------------------------------------------------------------------------------------------------------------------
We want your feedback! If you have any questions or suggestions regarding our contributing process/workflow, please reach out to us at karavi@dell.com.

**Comment by gallacher** [comment]
Released in 0.2.0 milestone
