### ISSUE TITLE
[BUG]: Karavi Observability installer script should use new flags for karavictl to support insecure=true/false and root-certificate

### ISSUE THREAD

**Issue by tdawe** [dell/karavi-observability#40]
**Describe the bug**
The Karavi Observablity installer should use the following new flags that are supported by the karavictl inject command:
- insecure=true/false
- root-certificate <location-of-root-ca>

The script should read from the ~/.karavi/config.json file to check if a rootCertificate was provided during installation of Karavi Authorization. If so, it should pass insecure=false and the root-certificate to the inject command for Observability.

**To Reproduce**
1. Use the install script to deploy Karavi Observability
2. By default, insecure=false is passed but no certificates are provided. This is preventing metrics-powerflex from accessing Karavi Authorization.
3. The current workaround would be to run `karavictl inject` manually for Observability.

**Expected behavior**
RootCA is mounted inside of the sidecar proxy for Observability, similar to the CSI driver.

**Screenshots**

**Logs**
If applicable, submit logs or stack traces from the affected services

**System Information (please complete the following information):**
 - OS/Version: [e.g. RHEL 7.6]
 - Kubernetes Version [e.g. 1.18]
 - karavi-metrics-powerflex Version: [e.g. 0.1.0-pre-release]
 - karavi-topology Version: [e.g. 0.1.0-pre-release]
 - Prometheus Version: [e.g. 2.22.0]
 - Grafana Version: [e.g. 7.3.2]
 - Grafana Dashboard Title(s): [e.g. Storage Pool and Storage Class Capacity]
 - Grafana Datatable Panel plugin configuration (can be provided as a screenshot)
 - Grafana Prometheus Datasource configuration (can be provided as a screenshot)
 - Grafana Pie Chart Panel plugin configuration (can be provided as a screenshot)
 - Grafana SimpleJson Datasource configuration (can be provided as a screenshot)
 - Additional Information...

**Additional context**

**Comment by ioeicicdsvc** [comment]
@tdawe: Thank you for submitting this issue!

The issue is currently awaiting triage. Please make sure you have given us as much context as possible.

If the maintainers determine this is a relevant issue, they will remove the needs-triage label and assign an appropriate priority label.

------------------------------------------------------------------------------------------------------------------------
We want your feedback! If you have any questions or suggestions regarding our contributing process/workflow, please reach out to us at karavi@dell.com.

**Comment by ioeicicdsvc** [comment]
link: 2870
