### ISSUE TITLE
[BUG]: Update otelCollector ports in getting started guide

### ISSUE THREAD

**Issue by alikdell** [dell/karavi-observability#44]
**Describe the bug**
For manual deployment of dashboards:
1) OtelCollector port is entered as 443 instead of 8443 in sample values file
2) Topology datasource has wrong url: https://karavi-topology.karavi.svc.cluster.local/ instead of https://karavi-topology:8443

**To Reproduce**
1.  Documentation update

**Expected behavior**
Update documentation so that manual deployment of dashboards work seamlessly.

**Screenshots**
N/A.

**Logs**
N/A

**System Information (please complete the following information):**
 - Grafana Dashboard Title(s): [e.g. Storage Pool and Storage Class Capacity]
 - Grafana Datatable Panel plugin configuration (can be provided as a screenshot)
 - Grafana Prometheus Datasource configuration (can be provided as a screenshot)
 - Grafana Pie Chart Panel plugin configuration (can be provided as a screenshot)
 - Grafana SimpleJson Datasource configuration (can be provided as a screenshot)
 - Additional Information...

**Additional context**

**Comment by ioeicicdsvc** [comment]
@alikdell: Thank you for submitting this issue!

The issue is currently awaiting triage. Please make sure you have given us as much context as possible.

If the maintainers determine this is a relevant issue, they will remove the needs-triage label and assign an appropriate priority label.

------------------------------------------------------------------------------------------------------------------------
We want your feedback! If you have any questions or suggestions regarding our contributing process/workflow, please reach out to us at karavi@dell.com.

**Comment by ioeicicdsvc** [comment]
link: 3024

**Comment by alikdell** [comment]
Fixed: https://github.com/dell/karavi-observability/pull/45
