### ISSUE TITLE
[BUG]: General documentation clean-up

### ISSUE THREAD

**Issue by shaynafinocchiaro** [dell/karavi-observability#69]
**Describe the bug**
General documentation review and cleanup:
- Layout and organization of documentation
- Documentation enhancements

**Comment by ioeicicdsvc** [comment]
@shaynafinocchiaro: Thank you for submitting this issue!

The issue is currently awaiting triage. Please make sure you have given us as much context as possible.

If the maintainers determine this is a relevant issue, they will remove the needs-triage label and assign an appropriate priority label.

------------------------------------------------------------------------------------------------------------------------
We want your feedback! If you have any questions or suggestions regarding our contributing process/workflow, please reach out to us at karavi@dell.com.

**Comment by ioeicicdsvc** [comment]
link: 3775

**Comment by oa72280emc** [comment]
For deployment of observability, there is a reference to values.yaml file however appears there is no values.yaml file associated with the git observability files. If those deploying use the online hyperlink - they may miss the sample  values.yaml which is a bit past half way down at the following link https://github.com/dell/karavi-observability/blob/main/docs/GETTING_STARTED_GUIDE.md

If the person deploying bypasses the offline manual steps, and only wishes to use online / helm they may confuse the values file for the myvalues.yaml that is created in the deployment of the CSI plugin as they use the same naming convention.

**Comment by gallacher** [comment]
@oa72280emc, thanks for the great feedback.  We will incorporate this feedback as part of the documentation fixes.
